apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-front
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-front
  template:
    metadata:
      labels:
        app: demo-front
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: demo-front
        image: twallace27603/inedemowebserver:2.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        env:
        - name: message
          value: "Updated"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: demo-front